### ISSUE TITLE
Content for AGU24 GMT/PyGMT pre-conference workshop

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/agu24workshop#1]
This issue is for discussing the full-day workshop schedule and logistics. We'll have 8.5 hours (including breaks) to fill with a mix of GMT and PyGMT course materials.

👉 **Draft outline**: https://hackmd.io/@pygmt/agu24workshop_outline

[Important dates](https://www.agu.org/annual-meeting/about#dates):
- 31 Jul 2024 - Final day to make changes to workshop abstract
- Early Nov 2024 - Early bird registration deadline
- Mid Nov 2024 - Last chance to reserve housing in AGU hotel block
- 8 Dec 2024 - Pre-conference workshop day

Some initial points to discuss:
- Given that there are 6 presenters (5 on-site), what topics should we cover? E.g. basic plotting to more advanced processing methods
- Length of tutorials, is 30-45 minutes per person ok?

**Note**: We don't need to finalize the schedule/outline before 31 Jul 2024. Feel free to put down your ideas anytime before September/October.

Deadline: Finish good draft by 20 November. Final draft by 30 November.

References:
- https://github.com/GenericMappingTools/gmt-for-geodesy
- https://github.com/GenericMappingTools/egu22pygmt/issues/1

**Comment by Esteban82** [comment]
I think I could give a lesson about animations with bash. 

Questions: 
1. Should we give the lesson live or can we use a recorded lesson (flipped classroom)?
2. Will be a limit for the ammount of parcipants? Which is it?

**Comment by yvonnefroehlich** [comment]
Thanks @weiji14 for starting this repro 🙂!

Looking at the list on HackMd I think I would like to work on the `pandas` related lesson.

**Comment by yvonnefroehlich** [comment]
> I think I could give a lesson about animations with bash.

@Esteban82 Great idea (maybe this is my change to give to `movie` module a try).

---------

I tried to also assign @andrebelem to this issue, but this seems not to be possible.

**Comment by andrebelem** [comment]
> I tried to also assign @andrebelem to this issue, but this seems not to be possible.
@yvonnefroehlich 
hummm curious. Did you get an error trying to assing me ?

**Comment by yvonnefroehlich** [comment]
> > I tried to also assign @andrebelem to this issue, but this seems not to be possible.
> > @yvonnefroehlich

>  hummm curious. Did you get an error trying to assing me ?

I think I found my mistake - I believe I included the "@" 🙁. Now it worked!

Oh - I apologize @maxrjones - I overlooked that you also tried to do this at the same time.

**Comment by weiji14** [comment]
Thanks everyone for getting started on this! I'd encourage everyone to put down ideas directly at https://hackmd.io/@pygmt/agu24workshop_outline if possible (to keep this issue thread from getting too long). @Esteban82 and @jhtong33, could you please create an account on [HackMD](https://hackmd.io) (can use your GitHub login) so I can invite you to edit that outline too?

> Questions:
> 1. Should we give the lesson live or can we use a recorded lesson (flipped classroom)?

I think the expectation is that this lesson would be given live. I'll ask the AGU staff though if we can use recordings.

> 2. Will be a limit for the ammount of parcipants? Which is it?

There is a cap of 80 seats for the workshop.

**Comment by Esteban82** [comment]
> @Esteban82 and @jhtong33, could you please create an account on [HackMD](https://hackmd.io) (can use your GitHub login) so I can invite you to edit that outline too?

I already have an account (with the same name than here).

**Comment by yvonnefroehlich** [comment]
Another point: People have to bring their own laptops for the workshop, correct? So, they should have installed the necessary packages before the workshop. Maybe it makes sense to consider some time at the beginning for helping here, if things were not successful for some participants?

**Comment by Esteban82** [comment]
Yes. they have to bring their laptops. And yes, we migth consider some time to help them. I think here that the best is to ask them to try to install the sofwtares before the workshop (I assume that they will have some days).

**Comment by jhtong33** [comment]
> Yes. they have to bring their laptops. And yes, we migth consider some time to help them. I think here that the best is to ask them to try to install the sofwtares before the workshop (I assume that they will have some days).


I think we need to prepare MacOS/ Windows installation tutorial If we expect they install before the workshop.

**Comment by weiji14** [comment]
Ok, thanks everyone who joined in on the meeting just now! We've settled on a solid outline at https://hackmd.io/@pygmt/agu24workshop_outline that will include 6x 45min tutorials + some preparation time for installation and a final 1.5 hours for a mini project! I'll open a PR in the next few days to add this outline to the repo/website.

Some notes:
- For installation, we aim to provide instructions by email before the workshop, so that participants can prepare their computers beforehand. But will also set aside 15min in case anyone faces issues.
- @maxrjones, you've been voluntold to do the tutorial on grids/xarray :slightly_smiling_face:
- @jhtong33 and @yvonnefroehlich will work together on a Geophysics/Seismology tutorial scheduled for the afternoon
- @andrebelem, I'll work with you on a 3D Topography related tutorial which can use either Planetary data or Antarctica
- @Esteban82 will do the final tutorial on GMT animations!

We've agreed to set a deadline of **20 November 2024** for a good draft that is ready for review, and a final final deadline of **30 November 2024** when the tutorial content should be up on the website at https://www.generic-mapping-tools.org/agu24workshop. Do feel free to start early though, and if anyone would like feedback on what to include in their tutorial, or wants to do a practice presentation, reach out to me or anyone else on the team. Cheers!

**Comment by Esteban82** [comment]
Hello.

I started to prepare my lesson on animations. I have some questions and comments.
1. What version of GMT are we going to ask them to install? 6.5? or can we expect to release 6.6 before the workshop? In June I gave a course on GMT using version 6.5 but then I asked them to use a more updated version of 6.6_dev provided by Joaquim for windows (all my students had windows) I think because of a bug in version 6.5.
2. When you can, I would like if you could share with me images and/or scripts from the previous lessons. It will help me to see which topics you have already explained and therefore I should not mention. Or also how to adapt them from PyGMT to GMT.

**Comment by andrebelem** [comment]
@weiji14 I have already read the outlines, and I'll prepare it and share it with you via DM.
> * @andrebelem, I'll work with you on a 3D Topography related tutorial which can use either Planetary data or Antarctica

@Esteban82, good point! I think 6.5 should be the best option, but... do you remember what kind of bug you experienced?

**Comment by Esteban82** [comment]
> @Esteban82, good point! I think 6.5 should be the best option, but... do you remember what kind of bug you experienced?

I think it was this issue (https://github.com/GenericMappingTools/gmt/issues/8403). Not very important. I think I won't have any problem using GMT 6.5.

**Comment by seisman** [comment]
> 1. can we expect to release 6.6 before the workshop

Maybe open an issue in the gmt repo so that we can have more discussions.

**Comment by Esteban82** [comment]
Maybe, for the animation tutorial it would go to fix the issue that the[ data server changes with movie](https://github.com/GenericMappingTools/gmt/issues/8209). But I can work with out it.

**Comment by weiji14** [comment]
:wave: Gentle reminder that first draft is due 20 Nov (let's go with [AoE](https://en.wikipedia.org/wiki/Anywhere_on_Earth)). I see a few Jupyter Notebook draft pull requests already, but let me know if you're intending to use a different format (e.g. Powerpoint slides exported to PDF, alongside some code/commands on a separate document). From what I can tell, we'll be naming the files `tut<number>_<topic>.<ext>`, e.g. `tut4_geophysics.ipynb`, so that they will be sorted in the `book/` folder in order.

Just to keep things moving along, I think we can review and merge some of the PRs by end of this week (22nd Nov), and then polish things up by the hard deadline end of this month (30th Nov, AoE).  If you are facing other issues and need some more time, do reach out early, so that others can jump in if needed. Cheers!

**Comment by yvonnefroehlich** [comment]
> 👋 Gentle reminder that first draft is due 20 Nov (let's go with [AoE](https://en.wikipedia.org/wiki/Anywhere_on_Earth)). I see a few Jupyter Notebook draft pull requests already, but let me know if you're intending to use a different format (e.g. Powerpoint slides exported to PDF, alongside some code/commands on a separate document). From what I can tell, we'll be naming the files `tut<number>_<topic>.ext`, e.g. `tut4_geophysics.ipynb`, so that they will be sorted in the `book/` folder in order.
> 
> Just to keep things moving along, I think we can review and merge some of the PRs by end of this week (22nd Nov), and then polish things up by the hard deadline end of this month (30th Nov, AoE). If you are facing other issues and need some more time, do reach out early, so that others can jump in if needed. Cheers!

Thanks @weiji14 🙂! This makes all sense to me!
I think my pandas / GeoPandas tutorial should be at the level ready for review. For the Geophysics (Seismology) tutorial, I feel the main part is already ready for review (maybe some formulations need some improvements), the part with plotting additional features needs probably a bit updated. 
Maybe I find time for reviewing on weekend.

**Comment by Esteban82** [comment]
Hello

I made a tutorial about animations here (https://github.com/GenericMappingTools/gmt-examples/pull/40#issue-2679399330) . Its ready to review. 

I had doubts about how to include content. So I made a complete version (with 2 tutorials) to publish it on that page. I have two doubts about the workshop: 
1. If I will have enough time (45 min) to explain it in the workshop. Maybe I can only give the tutorial 1. And let everyone see the tutorial 2 if they are interested. What do you think?
2. How to include that tutorial (written in rst) in this repository.

**Comment by weiji14** [comment]
Great to see that everyone has a draft already and that the reviews are ongoing! I'm struggling a bit to squeeze out time to review everything, but will at least endeavour to start merging PRs once I see either:

- 2 approvals (+all comments/suggestions addressed), or
- 1 approval + an ok :+1: sign from the person(s) who is responsible for the notebook that it's ready to merge

Note that the tutorial doesn't have to be 100% perfect to be approved/ready to merge, but I'd like to start to make sure that the website at https://www.generic-mapping-tools.org/agu24workshop has the proper structure in place (e.g. a proper table of contents) so let us know once it's 80% or 90% ready. It'll still be possible to make adjustments or fix typos afterwards.

> 2. How to include that tutorial (written in rst) in this repository.

@Esteban82, Jupyter Book supports RST docs too (see https://jupyterbook.org/en/stable/file-types/restructuredtext.html), so you can simply copy and paste your `animation.rst` file under https://github.com/GenericMappingTools/agu24workshop/tree/main/book, and add a line to the `book/_toc.yml` like so (note that you don't need to add the .rst extension):

```
- caption: Tutorials
  chapters:
  ...
  - file: animation
```

I've managed to copy your animation.rst file and built the page, which looks like this:

![image](https://github.com/user-attachments/assets/e6b03769-8faf-4a32-a8f5-b1d630ef1a0e)

> 1. If I will have enough time (45 min) to explain it in the workshop. Maybe I can only give the tutorial 1. And let everyone see the tutorial 2 if they are interested. What do you think?

Yes, maybe just give tutorial 1 in 45min, and then tutorial 2 could be something people work on in the final exercise/mini-project? Andre did something similar for the EGU22 short course in splitting the Mars tutorial into 2, see the Table of Contents at https://github.com/GenericMappingTools/egu22pygmt/blob/dee434490128748e3afc18d9ef31df8570ff7b6d/book/_toc.yml#L17-L19 (you'll need to split your RST file into two files though).

**Comment by yvonnefroehlich** [comment]
> Yes, maybe just give tutorial 1 in 45min, and then tutorial 2 could be something people work on in the final exercise/mini-project? Andre did something similar for the EGU22 short course in splitting the Mars tutorial into 2, see the Table of Contents at https://github.com/GenericMappingTools/egu22pygmt/blob/dee434490128748e3afc18d9ef31df8570ff7b6d/book/_toc.yml#L17-L19 (you'll need to split your RST file into two files though).

I think this is a good solution here! It's a bit similar to the "Additional feature section in the Geophysics (Seismology)" tutorial and the "Additional comments" sections. In this way, people have some freedom on what they want to take a closer look at, depending on their interests or what they need for their daily work.

**Comment by weiji14** [comment]
Ok, I just want to say **thank you** everyone for making all the tutorial materials, reviewing each others work, and opening issues to make so many suggestions on how to make this workshop better! We're a little behind on schedule from the original deadline, but I'm pleased to say that the Jupyter Book website at https://www.generic-mapping-tools.org/agu24workshop/ is looking at least 95%+ ready!

![image](https://github.com/user-attachments/assets/b82c91a3-4123-4736-b2a7-af6fcd89b5a9)

There are a few more nice-to-have things I'd like to see to get this closer to perfection:

- [x] Ensure that the instructions for Windows makes sense - #25
- [x] Standardize the frontmatter on every page to look consistent (topics covered, links to resources, etc) #29 
- [x] Lint all the code using pre-commit (as @maxrjones suggested at https://github.com/GenericMappingTools/agu24workshop/pull/15#issuecomment-2509904639)
- [ ] maybe other things?

If anyone wants to tackle any of the above, please open a PR directly to do so. I'm scrambling a bit to finish a whole bunch of stuff before my long flight on Saturday (and I imagine everyone is busy too), so I'd appreciate any help if you can find the time.

Looking forward to meeting everyone in person soon!

**Comment by yvonnefroehlich** [comment]
Yeah, it's really nice and cool to see that so many different processing and visualization tasks can be handled with GMT / PyGMT 🙂.

I should probably have the time to look at the front-matter consistency later the day.
_Edit_: Started PR #29 to work on a standardized frontmatter

**Comment by maxrjones** [comment]
We've completed everything on the checklist above, great work everyone! Let's open separate issues for any new last-minute changes
