### ISSUE TITLE
GMT stickers and coasters for the workshop?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/agu24workshop#13]
Paul made some GMT stickers and coasters when he was in Hawaii, and he sent me a few. I think it would be great to have some available for the workshop.

Does anyone know if there are still some left in Hawaii? If so, could they be sent to the AGU in time? Otherwise, I could bring some of mine to share.

What do you think?

**Comment by yvonnefroehlich** [comment]
Agree would be definitely nice to have some of these stickers and coasters to share during the workshop!

**Comment by maxrjones** [comment]
Do we know how many people will be attending? I also have some stickers/coasters and a relatively short flight to DC

**Comment by yvonnefroehlich** [comment]
> Do we know how many people will be attending? 

That's a good point! Currently I am at a project meeting, but I will be back on Monday. Maybe @weiji14 knows this or can figure it out? As people have to register separatly for any preworkshop there must be a registration list for each preworkshop. Maybe the submitting (first) author has access to this information through the AGU portal?

**Comment by weiji14** [comment]
I can't find any numbers on the AGU portal, so don't know how many people are registered. Let me try and email them and see if I can find that out. I've got some stickers left too and can bring them, probably good to hand them out during the memorial session too.

**Comment by weiji14** [comment]
Update: There's 30 people registered so far. Registration closes end of Monday 25 Nov.

**Comment by Esteban82** [comment]
Great. I emailed Garrett and he will send Max some merchadising available in Hawaii.

@weiji14 is it possible to contact the people who signed up before the workshop? It would be nice to be able to send them a survey for their prior knowledge.

**Comment by weiji14** [comment]
Yes, they said that I'll get a list of emails for all the participants sometime this week (after the registration closes), so we can send out the survey or any preparation info then.

**Comment by weiji14** [comment]
Ok, I'll close this issue since the goodies should be sorted. Have opened another issue about the survey questions at https://github.com/GenericMappingTools/agu24workshop/issues/20.
