### ISSUE TITLE
Incorrect display of images with in JN book on AGU website

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/agu24workshop#17]
The external images used in Tutorial 1 are correctly displayed in the JN on GitHub (https://github.com/GenericMappingTools/agu24workshop/blob/main/book/tut01_firstfigure.ipynb) but not in the Jupyter book on the AGU website (https://www.generic-mapping-tools.org/agu24workshop/tut01_firstfigure.html#coloring-and-add-map-element-frame-and-ticks):

| JN on GitHub | JB on AGU website |
| --- | --- |
| ![tut01_jn_github](https://github.com/user-attachments/assets/b9ac09a1-7a0b-4a98-a6ff-d4f61d15be6a) | ![tut01_jb_agu](https://github.com/user-attachments/assets/11dc12d0-e737-4fa0-9db6-a9e94ac22c87) |

**Comment by jhtong33** [comment]
I also noticed this problem on Friday. I can upload the original figure. 
It seems to need reference a figure with specific file path. (https://jupyterbook.org/en/stable/content/references.html)
