### ISSUE TITLE
Communication channels during the workshop

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/agu24workshop#22]
What methods should we have for communicating with users during the workshop? Options I've seen in the past:

- Hand out sticky notes so that participants can place a sticky note visible on their computer to flag an instructor for help
- Provide a slack or discord workspace so that participants can ask questions while the tutorials are ongoing

**Comment by weiji14** [comment]
> * Hand out sticky notes so that participants can place a sticky note visible on their computer to flag an instructor for help

Haven't heard of this one before, we could definitely give this sticky note idea a go (or just go with the traditional hand up :raised_hand_with_fingers_splayed:). Another way is to set up a hot desk where participants could go to to ask for help.

> * Provide a slack or discord workspace so that participants can ask questions while the tutorials are ongoing

The [GMT forum](https://forum.generic-mapping-tools.org/) is on Discourse 3.0 and has 'Channels' with real-time chat enabled already - https://blog.discourse.org/2023/01/discourse-3-0-is-here. Maybe we could set that a channel up for AGU24?

**Comment by maxrjones** [comment]
> > Hand out sticky notes so that participants can place a sticky note visible on their computer to flag an instructor for help

> Haven't heard of this one before, we could definitely give this sticky note idea a go (or just go with the traditional hand up 🖐️). Another way is to set up a hot desk where participants could go to to ask for help.

I think hand raising is nice for questions that might be relevant for the whole class, but there's value in a separate mechanism for individual help (e.g., why doesn't this work on my windows machine?). I like the help desk idea.

> > Provide a slack or discord workspace so that participants can ask questions while the tutorials are ongoing

> The GMT forum is on Discourse 3.0 and has 'Channels' with real-time chat enabled already - [blog.discourse.org/2023/01/discourse-3-0-is-here](https://blog.discourse.org/2023/01/discourse-3-0-is-here). Maybe we could set that a channel up for AGU24?

Interesting, I'll look into this option.

**Comment by weiji14** [comment]
> > > Hand out sticky notes so that participants can place a sticky note visible on their computer to flag an instructor for help
> 
> > Haven't heard of this one before, we could definitely give this sticky note idea a go (or just go with the traditional hand up 🖐️). Another way is to set up a hot desk where participants could go to to ask for help.
> 
> I think hand raising is nice for questions that might be relevant for the whole class, but there's value in a separate mechanism for individual help (e.g., why doesn't this work on my windows machine?). I like the help desk idea.

I see, hadn't thought about the whole class vs individual question aspect before, then let's bring some sticky notes (we could probably 'steal' some from the office :wink:). Let's try and gauge the venue size when we arrive to see if a help desk makes sense, usually that's for bigger workshops with a larger teacher:student ratio (e.g. 10 teachers:200 students). We might be ok with 7 teachers:31 students, and could just station ourselves around the room.

> > > Provide a slack or discord workspace so that participants can ask questions while the tutorials are ongoing
> 
> > The GMT forum is on Discourse 3.0 and has 'Channels' with real-time chat enabled already - [blog.discourse.org/2023/01/discourse-3-0-is-here](https://blog.discourse.org/2023/01/discourse-3-0-is-here). Maybe we could set that a channel up for AGU24?
> 
> Interesting, I'll look into this option.

Cool, and if that channels is set up, we can include it in the email sent to participants.

**Comment by weiji14** [comment]
Did you see the email from AGU about using the AGU24 mobile app to ask questions? I'm not sure if we should use that option (personally, I can't seem to login to the app because it says I don't have Chrome installed on my phone...), or just stick to the GMT forum channel, or just the sticky note/hand-raising method.

**Comment by maxrjones** [comment]
yeah, let's not rely on AGU technology 😅

**Comment by andrebelem** [comment]
Hey guys ( @weiji14 @yvonnefroehlich @jhtong33 @Esteban82 @maxrjones )
Wishing everyone at the AGU24 workshop the best of luck! May it be a productive and inspiring session !
❤️
