### ISSUE TITLE
Tutorial 4 - Geophysics (Seismology): Ideas and basic concept

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/agu24workshop#6]
Within the pre-workshop we plan to have a tutorial covering topics regarding geophysics / seismology (see Tutorial 4 in the schedule table at https://hackmd.io/JtJP8TyNQBiEUNGHZwfhhg#Schedule). This issue should help to bundel ideas for topics and the basic structure before starting to work on a JN in PR to avoid double work 🙂. Feel free to edit this issue and add your own ideas :rocket:.

**Creator / presenter**
- @jhtong33 
- @yvonnefroehlich

**Possible topics**
- focal mechanisms (beach balls): `Figure.meca`
 -> https://www.pygmt.org/dev/gallery/seismology/meca.html
 -> https://github.com/GenericMappingTools/pygmt/pull/2550
- geology (faults): `Figure.plot` (line fronts)
 -> https://www.pygmt.org/dev/gallery/lines/linefronts.html
- anisotropy (bars): `Figure.plot` (orientated bars), `Figur.velo` (so far not used by @yvonnefroehlich )
  -> https://www.pygmt.org/dev/gallery/seismology/velo_arrow_ellipse.html (actuall on velocity arrows)

**Comment by jhtong33** [comment]
I think "seismic anisotropy" might not be simple for non-seismologists.

I have some ideas: 
1. profile, seismicity, and focal mechanisms (maybe Mw>6)
2. relative plate motion(velo) ? 
3. lithosphere thickness (xyz2grd/grdimage/grdcontour) https://ds.iris.edu/ds/products/emc-cam2016/ 
4. geology(faults and volcanos)

**Comment by Esteban82** [comment]
I think it is better NOT to explain about focal mechanisms. It is a specific module just for that. For those who are not interested, it will not bring them anything. For those who are interested, I think they can learn it on their own. It is a simple module. I would mention that it exists.

**Comment by yvonnefroehlich** [comment]
> I think "seismic anisotropy" might not be simple for non-seismologists.

> I think it is better NOT to explain about focal mechanisms. It is a specific module just for that. For those who are not interested, it will not bring them anything. For those who are interested, I think they can learn it on their own. It is a simple module. I would mention that it exists.

Yeah, probably you are right, focal mechanisms and seismic anisotropy are specifically related to seismology.

**Comment by yvonnefroehlich** [comment]
For a more general set up we could do something in the direction of:

- ``xyz2grd``: Preparing the data to be a GMT-ready grid; depends on the format of the used data
- ``grdimage``: Plot the grid with color-coding; add a colorbar
- ``grdcontour``: Add contour lines on top of the map
- ``grdprojekt``, ``grdtrack``: Mark a profile within the study area, extract and plot the values along this profile in a Cartesian plot (see also https://www.pygmt.org/dev/gallery/images/cross_section.html)

Maybe we can have an “Additional task” section at the end of the tutorial with suggestions for further adjustments and give some links to additional resources or examples:
- Chosen another study area with focus on earthquakes, faults, or volcanos and plot the related feature on top of the map.
- Add additional things like the plate motion, the beachball of a specific earthquake or anisotropy bars.

**Comment by jhtong33** [comment]
In my first-figure tutorial, I have already cover grdimage, makecpt, and colorbar. 
I think `xyz2grd`, `grdcontour`, `grdtrack` will be great direction. 
Since we have 45 minutes, perhaps we can add simple earthquake profile and basic beachball. (see also https://www.nature.com/articles/s41467-020-14745-8/figures/1)

**Comment by yvonnefroehlich** [comment]
> In my first-figure tutorial, I have already cover grdimage, makecpt, and colorbar.

Ah, nice. And this is actually good, so we can save some time. Then we focus on `grdcontour` in this tutorial and we do not need to spend much time on explaining `makecpt` and `colorbar` again.

**Comment by yvonnefroehlich** [comment]
> I think `xyz2grd`, `grdcontour`, `grdtrack` will be great direction.
> Since we have 45 minutes, perhaps we can add simple earthquake profile and basic beachball. (see also https://www.nature.com/articles/s41467-020-14745-8/figures/1)

As we now have a general idea of what we want to teach in this tutorial, I think we can start creating the tutorial. Regarding adding details, I think the easiest way is to (more or less) finish the "`xyz2grd`, `grdcontour`, `grdtrack`" part; and based on how much time we have left we can extend the tutorial regarding more features (seismicity, beachballs, etc.). 
What is the best way to work on this tutorial as a team? I think one of us can just start and open a PR with a rough draft and then we go through this and give suggestions and add ideas.

_Update_: I submitted PR # 8 with a rough set up of the JN. Feel free to add suggestions for code and docs 🙂.
