### ISSUE TITLE
Make review of Jupyter notebooks more convenient

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/agu24workshop#9]
Reviewing Jupyter notebooks directly on GitHub is not very convenient. [GitNotebooks](https://gitnotebooks.com/) can make the review process easier. As an example, I use PR #4 

GitHub: https://github.com/GenericMappingTools/agu24workshop/pull/4/files
gitnotebooks: https://gitnotebooks.com/GenericMappingTools/agu24workshop/pull/4

Maybe this is helpful for use. Feel free to suggest any other tool which you think can be useful.

(modified from issue https://github.com/GenericMappingTools/pygmt-paper-figures/issues/3)

**Comment by weiji14** [comment]
Hmm, I'm having some trouble putting a review in with gitnotebooks. Am getting some error about `Unprocessable Entity: "Pull request review thread path diff too large and Pull request review thread diff hunk can't be blank"`

![image](https://github.com/user-attachments/assets/ac4181e9-1e1f-4e56-b0fa-e3ae6f9e05d7)

Have you seen this before @yvonnefroehlich? I managed to use GitNotebooks for another repo recently, but not sure why I'm getting this error here.

**Comment by yvonnefroehlich** [comment]
Hm. Yes, I also get this error and sofar I could not figure out why this is.
And no, so far I did not face this issue in other repos (even without having writting permissions).

**Comment by yvonnefroehlich** [comment]
For me, it works to comment on PR #4 (https://github.com/GenericMappingTools/agu24workshop/pull/4#discussion_r1854566318) and PR #10 (https://github.com/GenericMappingTools/agu24workshop/pull/10#discussion_r1854590425) and but not on PR #8 via GitNotebooks. The PRs #4 and #8 were opened by me, PR #10  not. For the PRs #4 and #10, it's possible for me to display the diffs directly on GitHub (e.g., https://github.com/GenericMappingTools/agu24workshop/pull/4/files), but for PR #8 I get the information "1,463 additions, 0 deletions not shown because the diff is too large. Please use a local Git client to view these changes." (https://github.com/GenericMappingTools/agu24workshop/pull/8/files). So, I am wondering if also GitNotebooks has a limitation for the amount of diffs supported in one PR?

**Comment by yvonnefroehlich** [comment]
So, I think I figured out the reason for this issue: It's related to the images shown within the JN, which are displayed as super long strings (diffs) when the JN is displayed as plain text. For testing, I out-commented `Figure.show` within the JN in PR #8 (https://github.com/GenericMappingTools/agu24workshop/pull/8/commits/334ef23b3791a366f59de3ee698034344dbe58f2). After this, I am able to submit review comments via GitNotebooks (https://github.com/GenericMappingTools/agu24workshop/pull/8#discussion_r1855165298). When adding `Figure.show` back (https://github.com/GenericMappingTools/agu24workshop/pull/8/commits/44a7bf4f07962d377f80c0a61859faa256dd7f8b), I am again not able to submit a review via GitNotebooks.

_Edit_:
Temporary for the JN of PR #8, only the finale image is displayed (https://github.com/GenericMappingTools/agu24workshop/pull/8/commits/41116f8f9e3028ba27e4293bb560cf43dfae5d8c). For me, it is now possible to submit a review via GitNotebooks.

_Edit_:
Now, all images are displayed within this JN.

**Comment by yvonnefroehlich** [comment]
Maybe it works, after running "Clear output of All Cells", then the large diffs related to the output images are ago.

**Comment by weiji14** [comment]
The tutorial Jupyter Notebooks are completed now, so I think we can close this.
